/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ball(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Premier Ball.glb')
  console.log("created")
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_id36.geometry}
        material={materials['74']}
        position={[-0.01, 0.02, 0.21]}
        scale={[0, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_id48.geometry}
        material={materials['76']}
        position={[-0.01, 0.01, 0.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_id38.geometry}
        material={materials['78']}
        position={[-0.01, 0.01, 0.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_id44.geometry}
        material={materials['80']}
        position={[-0.01, 0.01, 0.41]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh geometry={nodes.mesh_id31.geometry} material={materials['82']} position={[-0.01, 0.13, 0.21]} scale={0} />
      <mesh
        geometry={nodes.mesh_id33.geometry}
        material={materials['84']}
        position={[-0.01, -0.1, 0.21]}
        rotation={[-Math.PI, 0, 0]}
        scale={0}
      />
    </group>
  )
}

useGLTF.preload('/Premier Ball.glb')
