/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shanti (https://sketchfab.com/shanti.rize)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/weed-bud-bfeabeb5adff45b79d3b3b543bb673d0
title: Weed Bud
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cannabis(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/cannabis.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -58.69, -6.32]} rotation={[1.57, 0, 0]} scale={[1, 1, 1]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.meshNode_Material_u1_v1_0.geometry}
            material={nodes.meshNode_Material_u1_v1_0.material}
          />
          <mesh
            geometry={nodes.meshNode_Material_u1_v1_0_1.geometry}
            material={nodes.meshNode_Material_u1_v1_0_1.material}
          />
          <mesh
            geometry={nodes.meshNode_Material_u1_v1_0_2.geometry}
            material={nodes.meshNode_Material_u1_v1_0_2.material}
          />
          <mesh
            geometry={nodes.meshNode_Material_u1_v1_0_3.geometry}
            material={nodes.meshNode_Material_u1_v1_0_3.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cannabis.gltf')
