/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rocket(props) {
  const group = useRef()
  const { nodes } = useGLTF('/Rocket.gltf')
 // const { actions } = useAnimations(animations, group);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.2, 3.74]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh
          geometry={nodes.VentMain_1.geometry}
          material={nodes.VentMain_1.material}
          position={[0, 0.11, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
      </group>
      <group position={[0, 1.2, 3.51]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1, 1, 1]}>
        <mesh
          geometry={nodes.VentSub_1.geometry}
          material={nodes.VentSub_1.material}
          position={[0, 0.06, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
      </group>
      <group position={[-0.2, 0.88, -2.9]} rotation={[-Math.PI / 2, 0, Math.PI]}>
        <group position={[0.55, 0.04, 0]} rotation={[0, 0, -1.84]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.FlapRight_1.geometry}
            material={nodes.FlapRight_1.material}
            position={[0, 0.2, 0]}
            rotation={[Math.PI / 2, -1.3, 0]}
          />
        </group>
        <mesh
          geometry={nodes.WingRight_1.geometry}
          material={nodes.WingRight_1.material}
          position={[0, 0.24, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
      </group>
      <group position={[0.19, 0.88, -2.9]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <group position={[-0.55, 0.04, 0]} rotation={[0, 0, 1.84]} scale={[1, 1, 1]}>
          <mesh
            geometry={nodes.FlapLeft_1.geometry}
            material={nodes.FlapLeft_1.material}
            position={[0, 0.2, 0]}
            rotation={[Math.PI / 2, 1.3, 0]}
          />
        </group>
        <mesh
          geometry={nodes.WingLeft_1.geometry}
          material={nodes.WingLeft_1.material}
          position={[0, 0.24, 0]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
      </group>
      <group position={[-0.69, 1.94, 0.65]} rotation={[-0.49, -0.02, -0.03]} scale={[1, 1, 1]}>
        <mesh
          geometry={nodes.SwitchRight_1.geometry}
          material={nodes.SwitchRight_1.material}
          position={[0, 0, 0]}
          rotation={[0.49, 0.03, 0.02]}
        />
      </group>
      <group position={[0.69, 1.94, 0.65]} rotation={[-0.49, 0.02, 0.03]}>
        <mesh
          geometry={nodes.SwitchLeft_1.geometry}
          material={nodes.SwitchLeft_1.material}
          position={[0, 0, 0]}
          rotation={[0.49, -0.03, -0.02]}
        />
      </group>
      <group name="WingMain" position={[0, 1.76, -2.72]} rotation={[-0.38, 0, 0]}>
        <mesh
          geometry={nodes.WingMain_1.geometry}
          material={nodes.WingMain_1.material}
          position={[0, 0, 0]}
          rotation={[0.38, 0, 0]}
        />
      </group>
      <mesh geometry={nodes.Bike.geometry} material={nodes.Bike.material} />
    </group>
  )
}

useGLTF.preload('/Rocket.gltf')
